[pytest]
# Async configuration
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function

# Test discovery & execution options
testpaths = tests
#addopts = -m "not performance"
#markers =
#    performance: tests for the LLM performance analyzer

# Custom framework options
#generate_agent_performance_report = false

# Terminal (CLI) Live Logging
log_cli = true
log_cli_level = WARNING
log_cli_format = %(asctime)s [%(levelname)8s] %(name)s: %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

# Internal Log Capture (Attached to pytest reports)
log_level = WARNING

# File Logging (Set to DEBUG for deeper issue diagnosis)
log_file = pytest.log
log_file_level = WARNING
log_file_format = %(asctime)s [%(levelname)8s] %(name)s: %(message)s (%(filename)s:%(lineno)s)
log_file_date_format = %Y-%m-%d %H:%M:%S